version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pydocstyle
    versions:
    - 5.1.1
  - dependency-name: requests-mock
    versions:
    - 1.8.0
